Traceback (most recent call last):
  File "/Users/patrickmckeen/Documents/GitHub/McKeenADS/GeneralizedADS/ADCS/run_sim.py", line 1240, in run_sim_wrapper
    run_sim(orb_file,state0,copy.deepcopy(real_sat),adcsys,base_title,tf=tf,dt = dt,rand=False,plot_3D_err = False)
  File "/Users/patrickmckeen/Documents/GitHub/McKeenADS/GeneralizedADS/ADCS/run_sim.py", line 224, in run_sim
    control = adcsys.ADCS_update(j2000_0+(t-t0)*sec2cent,sens,gps_sens,state_truth = state,first_ADCS = first_ADCS)
  File "/Users/patrickmckeen/Documents/GitHub/McKeenADS/GeneralizedADS/ADCS/src/sat_ADCS_ADCS/ADCS.py", line 511, in ADCS_update
    self.estimation_update(sens,t,self.current_ctrl,truth = state_truth)
  File "/Users/patrickmckeen/Documents/GitHub/McKeenADS/GeneralizedADS/ADCS/src/sat_ADCS_ADCS/ADCS.py", line 646, in estimation_update
    self.estimator.update(control,sens,self.orbit_estimator.current_state_estimate,truth = truth)
  File "/usr/local/lib/python3.10/site-packages/sat_ADCS_estimation/attitude_estimator.py", line 183, in update
    out,extra = self.update_core(control_vec,sensors_in,os,which_sensors)
  File "/usr/local/lib/python3.10/site-packages/sat_ADCS_estimation/attitude_SRUKF.py", line 264, in update_core
    raise np.linalg.LinAlgError('NAN IN COV')
numpy.linalg.LinAlgError: NAN IN COV
